name: flutter_practice_1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.0.0
  flutter_lints: ^4.0.0
  build_runner: ^2.1.0
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
